services:
  - type: web
    name: godseye
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: CESIUM_ION_TOKEN
        sync: false
      - key: TOMTOM_API_KEY
        sync: false
      - key: FIRMS_MAP_KEY
        sync: false
      - key: AISSTREAM_API_KEY
        sync: false
      - key: OPENSKY_CLIENT_ID
        sync: false
      - key: OPENSKY_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
